# Generated by Django 5.2.6 on 2025-09-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_setup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='selected_concentration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
