# Generated by Django 5.2.6 on 2025-09-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_has_completed_setup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="completed_courses_json",
            field=models.TextField(blank=True, default="[]"),
        ),
    ]
