# Generated by Django 5.2.6 on 2025-09-23 23:11

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_completed_courses_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="completed_courses_json",
            field=models.JSONField(
                default=list, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
