# Generated by Django 5.2.6 on 2025-09-28 17:46

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_customuser_completed_courses_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="planned_courses_json",
            field=models.JSONField(
                default=list, encoder=django.core.serializers.json.DjangoJSONEncoder
            ),
        ),
    ]
