# Generated by Django 5.2.6 on 2025-11-16 22:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_planned_courses_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', help_text="Optional short key/tag for the memory, e.g. 'major' or 'no_mornings'", max_length=150)),
                ('value', models.TextField(help_text='Human-readable memory content (short).')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional JSON metadata (source, confidence, origin_message_id, etc.)')),
                ('source', models.CharField(default='chat', help_text='Origin (chat, manual, import, ai_extracted, etc.)', max_length=50)),
                ('pinned', models.BooleanField(default=False, help_text='If pinned, treat as higher priority when retrieving context')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of the memory item', on_delete=django.db.models.deletion.CASCADE, related_name='memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pinned', '-updated_at'],
                'indexes': [models.Index(fields=['user', 'key'], name='accounts_me_user_id_67f3a0_idx'), models.Index(fields=['user', 'updated_at'], name='accounts_me_user_id_dc7961_idx')],
            },
        ),
    ]
