# Generated by Django 5.2.6 on 2025-11-23 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_memory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ['-pinned', '-updated_at'], 'verbose_name': 'Memory', 'verbose_name_plural': 'Memories'},
        ),
    ]
