# Generated by Django 5.2.6 on 2026-01-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_memory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('curriculum_code', models.CharField(max_length=50)),
                ('term_id', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('credits', models.IntegerField(default=0)),
                ('design_credits', models.IntegerField(default=0)),
                ('component', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('prerequisites', models.CharField(blank=True, max_length=200)),
                ('corequisites', models.CharField(blank=True, max_length=200)),
                ('term', models.CharField(blank=True, max_length=50)),
                ('OL', models.BooleanField(default=False, verbose_name='Online Available')),
                ('OL_only', models.BooleanField(default=False, verbose_name='Online Only')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('concentration', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('graduation_requirements', models.JSONField(blank=True, default=dict)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('ai_recommendation_settings', models.JSONField(blank=True, default=dict)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('curriculum_code', models.CharField(max_length=50)),
                ('term_id', models.CharField(max_length=50)),
                ('term_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('trimester', models.CharField(blank=True, max_length=10)),
                ('recommended_trimester', models.JSONField(blank=True, default=list)),
                ('typical_next_terms', models.JSONField(blank=True, default=list)),
                ('critical_courses', models.JSONField(blank=True, default=list)),
                ('min_credits', models.IntegerField(blank=True, null=True)),
                ('max_credits', models.IntegerField(blank=True, null=True)),
                ('total_credits_in_term', models.IntegerField(blank=True, null=True)),
                ('term_info', models.JSONField(blank=True, default=dict)),
                ('concentration', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Term',
                'verbose_name_plural': 'Terms',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='dashboard_card_style',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
